### ISSUE TITLE
inconsistent pheno tables between gene and transcript datasets

### ISSUE THREAD

**Issue by jvanheld** [leekgroup/recount#19]
Dear recount team,

First of all, congratulations this great resource, which I am regularly using for training and research. 

I have a problem with several studies (e.g. SRP042620), where the structure of the pheno table extracted from  RData files downloaded from recount differs between transcript and gene datasets. 

For the gene dataset, the characteristics field is a CompressedCharacteristics (as expected)

```
> phenoTable <- colData(rse_gene) ## phenotype per run
> class(phenoTable$characteristics)
[1] "CompressedCharacterList"
attr(,"package")
[1] "IRanges"
```

For the transcript dataset, it is a vector

```
> phenoTable <- colData(rse_tx) ## phenotype per run
> class(phenoTable$characteristics)
[1] "character"
```

Is there a way to fix this ?

Many thanks,

Jacques van Helden

**Comment by lcolladotor** [comment]
Hi,

This is a duplicate question of https://support.bioconductor.org/p/116480/ that includes the answer at https://support.bioconductor.org/p/116480/#124335

The data hasn't changed since then, so the answer should still apply (which you reported as working in https://support.bioconductor.org/p/116480/#125723)

Best,
Leo
